import { useEffect, useMemo, useState } from "react";
import { Search, X } from "lucide-react";

const departments = ["Computer Science and Engineering","Computer Engineering","Civil Engineering","Chemical Engineering","Computer Applications","Computer Science","Computer Science and Business Systems","Computer Science and Design","Cyber Security","Data Science","Electrical and Electronics Engineering","Electronics and Communication Engineering","Electronics and Instrumentation Engineering","Information Technology","Information Science and Engineering","Mechanical Engineering","Mechatronics Engineering","Automobile Engineering","Aeronautical Engineering","Artificial Intelligence and Data Science","Artificial Intelligence and Machine Learning","Biotechnology","Biomedical Engineering","Production Engineering","Industrial Engineering"];
const careers = ["Java Backend Developer","Full Stack Developer","Frontend Developer","Python Developer","AI/ML Engineer","Data Analyst","Cloud Engineer","Cybersecurity Analyst"];

const inputClass = "w-full h-12 mt-2 rounded-xl border border-slate-200 bg-white px-4 text-slate-800 outline-none focus:border-teal-400";
function Field({label,value,onChange,placeholder,type="text"}) { return <div><label className="text-sm font-semibold text-slate-700">{label}</label><input required type={type} value={value||""} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className={inputClass}/></div>; }
function SectionTitle({number,title}) { return <div className="flex items-center gap-3 mt-9 mb-5"><span className="text-sm font-bold text-teal-600">{number}</span><h2 className="text-xl font-bold text-slate-900">{title}</h2></div>; }

export default function PreviousRegister({student,updateStudent,onRegister,onLogin}) {
  const [collegeSearch,setCollegeSearch]=useState(student.collegeId||student.college||"");
  const [colleges,setColleges]=useState([]); const [showColleges,setShowColleges]=useState(false);
  const [departmentSearch,setDepartmentSearch]=useState(student.department||""); const [showDepartments,setShowDepartments]=useState(false);
  const [careerSearch,setCareerSearch]=useState(""); const [showCareers,setShowCareers]=useState(false);
  const [selectedCareers,setSelectedCareers]=useState(student.careers||[]);
  useEffect(()=>{setSelectedCareers(student.careers||[]);setCollegeSearch(student.collegeId||student.college||"");setDepartmentSearch(student.department||"");},[student.collegeId,student.college,student.department,student.careers]);
  useEffect(()=>{fetch("https://skillproof-backend-1.onrender.com/api/students/colleges").then(r=>r.ok?r.json():{colleges:[]}).then(d=>setColleges(d.colleges||[])).catch(()=>setColleges([]));},[]);
  const collegeMatches=useMemo(()=>{const q=collegeSearch.trim().toLowerCase();return (q?colleges.filter(c=>`${c.name||""} ${c.college_id||""}`.toLowerCase().includes(q)):colleges).slice(0,8);},[collegeSearch,colleges]);
  const departmentMatches=useMemo(()=>{const q=departmentSearch.trim().toLowerCase();return q?departments.filter(d=>d.toLowerCase().startsWith(q)):departments;},[departmentSearch]);
  const careerMatches=useMemo(()=>{const q=careerSearch.trim().toLowerCase();return careers.filter(c=>!selectedCareers.includes(c)&&c.toLowerCase().includes(q));},[careerSearch,selectedCareers]);
  const chooseCollege=c=>{updateStudent("college",c.name||"");updateStudent("collegeId",c.college_id||"");setCollegeSearch(c.college_id||c.name||"");setShowColleges(false);};
  const addCareer=c=>{if(selectedCareers.length>=3)return;const next=[...selectedCareers,c];setSelectedCareers(next);updateStudent("careers",next);setCareerSearch("");};
  const removeCareer=c=>{const next=selectedCareers.filter(x=>x!==c);setSelectedCareers(next);updateStudent("careers",next);};
  const valid=Boolean(student.name&&student.email&&student.password&&student.collegeId&&student.college&&student.collegeEmail&&student.department&&student.graduationYear&&selectedCareers.length);
  return <div className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><div className="max-w-6xl mx-auto bg-white rounded-3xl border border-slate-200 shadow-sm px-5 md:px-10 py-8 md:py-9"><h1 className="text-4xl md:text-5xl font-bold tracking-tight">Create your profile</h1><p className="text-lg text-slate-500 mt-3">Use your registered College ID so your institution can track your verified progress.</p>
    <form onSubmit={onRegister}>
      <SectionTitle number="01" title="Personal information"/><div className="grid md:grid-cols-2 gap-4"><Field label="Full name" value={student.name} onChange={v=>updateStudent("name",v)} placeholder="Your name"/><Field label="Personal email" value={student.email} onChange={v=>updateStudent("email",v)} placeholder="you@example.com" type="email"/><Field label="Password" value={student.password} onChange={v=>updateStudent("password",v)} placeholder="Create a password" type="password"/><Field label="College email ID" value={student.collegeEmail} onChange={v=>updateStudent("collegeEmail",v)} placeholder="you@college.edu" type="email"/></div>
      <div className="mt-5 relative"><label className="block text-sm font-semibold text-slate-700 mb-2">Registered College ID</label><input required value={collegeSearch} onFocus={()=>setShowColleges(true)} onChange={e=>{setCollegeSearch(e.target.value);setShowColleges(true);}} placeholder="Enter College ID or college name..." className={inputClass}/>{showColleges&&collegeSearch.trim()&&<div className="absolute z-30 left-0 right-0 mt-2 max-h-72 overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-xl">{collegeMatches.length?collegeMatches.map(c=><button key={c.college_id||c.name} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>chooseCollege(c)} className="w-full text-left px-4 py-3 hover:bg-teal-50 border-b border-slate-50"><p className="font-semibold">{c.name}</p><p className="text-xs text-teal-700">College ID: {c.college_id}</p></button>):<div className="px-4 py-3 text-sm text-slate-500">No registered college found.</div>}</div>}</div>
      <div className="mt-3 rounded-xl bg-teal-50 border border-teal-100 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-teal-700">Registered college</p><p className="text-sm font-bold mt-1">{student.college||"Not selected"}</p><p className="text-xs text-teal-700 mt-1">College ID: {student.collegeId||"Not selected"}</p></div>
      <div className="grid md:grid-cols-2 gap-4 mt-4"><div className="relative"><label className="text-sm font-semibold text-slate-700">Department</label><input required value={departmentSearch} onFocus={()=>setShowDepartments(true)} onChange={e=>{setDepartmentSearch(e.target.value);updateStudent("department",e.target.value);setShowDepartments(true);}} placeholder="Computer Science" className={inputClass}/>{showDepartments&&<div className="absolute z-30 left-0 right-0 mt-2 max-h-64 overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-xl">{departmentMatches.map(d=><button key={d} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>{setDepartmentSearch(d);updateStudent("department",d);setShowDepartments(false);}} className="w-full text-left px-4 py-3 text-sm hover:bg-teal-50 border-b border-slate-50">{d}</button>)}</div>}</div><Field label="Graduation year" value={student.graduationYear} onChange={v=>updateStudent("graduationYear",v)} placeholder="2027" type="number"/></div>
      <SectionTitle number="02" title="Target careers"/><div className="relative"><div className="min-h-14 w-full rounded-xl border border-slate-200 bg-white p-2 flex flex-wrap gap-2 items-center">{selectedCareers.map(c=><span key={c} className="inline-flex items-center px-3 py-1.5 rounded-full bg-teal-50 border border-teal-200 text-teal-800 text-sm">{c}<button type="button" onClick={()=>removeCareer(c)} className="ml-2"><X size={14}/></button></span>)}{selectedCareers.length<3&&<div className="flex-1 min-w-48 flex items-center"><Search size={16} className="text-slate-400 ml-1 mr-2"/><input value={careerSearch} onFocus={()=>setShowCareers(true)} onChange={e=>{setCareerSearch(e.target.value);setShowCareers(true);}} placeholder="Search target careers..." className="flex-1 h-9 outline-none text-sm"/></div>}</div>{showCareers&&selectedCareers.length<3&&<div className="absolute z-30 left-0 right-0 mt-2 max-h-72 overflow-y-auto rounded-xl border border-slate-200 bg-white shadow-xl">{careerMatches.map(c=><button key={c} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>addCareer(c)} className="w-full text-left px-4 py-3 text-sm hover:bg-teal-50">{c}</button>)}</div>}</div><p className="text-xs text-slate-400 mt-2">Select up to 3 target careers.</p>
      <button disabled={!valid} className="w-full h-12 mt-6 rounded-xl bg-slate-900 text-white font-semibold disabled:opacity-40">Create SkillProof profile</button>
    </form><p className="text-center text-sm text-slate-500 mt-6">Already have an account? <button type="button" onClick={onLogin} className="text-teal-700 font-semibold">Sign in</button></p>
  </div></div>;
}
