export function studentDataPlugin() {
  return {
    name: "skillproof-student-data",
    enforce: "pre",
    transform(code, id) {
      if (!id.endsWith("/src/App.jsx")) return null;
      let next = code;
      next = next.replace(/const login = async \(e\) => \{[\\s\\S]*?(?=\n  const register =)/, `const login = async (e) => { e.preventDefault(); try { const data = await api("/auth/login", { method: "POST", body: JSON.stringify({ email: student.email, password: student.password }) }); if (data.user?.role && data.user.role !== "student") throw new Error("This account is not a student account. Use the correct role login."); if (data.token) localStorage.setItem("skillproof_token", data.token); const u = data.user || {}; saveStudent({ ...student, name: u.name || student.name, email: u.email || student.email, college: u.college || student.college, collegeId: u.college_identifier || u.college_id || u.collegeId || student.collegeId, collegeEmail: u.college_email || student.collegeEmail || "", department: u.department || student.department, graduationYear: u.graduation_year || u.graduationYear || student.graduationYear, careers: u.careers || student.careers || [], skills: u.skills || student.skills || [] }); setUserRole("student"); setScreen("app"); setActivePage("dashboard"); } catch (error) { alert(error.message || "Student login failed."); } };`);
      next = next.replace(/const register = async \(e\) => \{[\\s\\S]*?(?=\n  const logout =)/, `const register = async (e) => { e.preventDefault(); const normalized = { ...student, careers: student.careers || [], skills: student.skills || [] }; try { const data = await api("/auth/register", { method: "POST", body: JSON.stringify({ name: normalized.name, email: normalized.email, password: normalized.password, role: "student", college: normalized.college, collegeId: normalized.collegeId, college_id: normalized.collegeId, college_email: normalized.collegeEmail, department: normalized.department, graduationYear: normalized.graduationYear, graduation_year: normalized.graduationYear, careers: normalized.careers, skills: normalized.skills }) }); if (data.token) localStorage.setItem("skillproof_token", data.token); const u = data.user || {}; saveStudent({ ...normalized, college: u.college || normalized.college, collegeId: u.college_identifier || u.college_id || normalized.collegeId, collegeEmail: u.college_email || normalized.collegeEmail || "", department: u.department || normalized.department, graduationYear: u.graduation_year || normalized.graduationYear, careers: u.careers || normalized.careers }); setUserRole("student"); setScreen("app"); setActivePage("dashboard"); } catch (error) { alert(error.message || "Registration failed. Please try again."); } };`);
      next = next.replace(/const valid=student\.name&&student\.email&&student\.password&&student\.collegeId&&student\.college&&student\.collegeEmail&&student\.department&&student\.graduationYear&&selectedCareers\.length;/, `const valid=student.name&&student.email&&student.password&&student.collegeId&&(student.college||exact?.name)&&student.collegeEmail&&student.department&&student.graduationYear&&selectedCareers.length;`);
      next = next.replace(/<Field label="College name" value=\{student\.college\|\|""\} readOnly placeholder="Automatically filled from College ID"\/>/, `<Field label="College name" value={exact?.name || student.college || ""} readOnly placeholder="Automatically filled from College ID"/>`);
      return next === code ? null : { code: next, map: null };
    },
  };
}
