import { useMemo, useState } from "react";
import { ArrowRight, Award, Bell, BookOpen, BriefcaseBusiness, CheckCircle2, ChevronRight, Code2, FolderKanban, Github, LayoutDashboard, Lightbulb, Pencil, Search, Settings, ShieldCheck, Sparkles, Target, User, Users, Wrench } from "lucide-react";

const DEFAULT_CAREERS = ["Frontend Developer", "Full Stack Developer", "Java Backend Developer"];
const STAGES = [
  { name: "Web Foundations", max: 60, description: "Understand browsers, HTTP, web structure and developer tools." },
  { name: "HTML & CSS", max: 85, description: "Build semantic, responsive and maintainable web interfaces." },
  { name: "JavaScript", max: 80, description: "Master modern JavaScript, DOM events, async code and modules." },
  { name: "React", max: 75, description: "Build interactive user interfaces with React." },
  { name: "Responsive Design", max: 70, description: "Create mobile-first, responsive layouts." },
  { name: "Git & GitHub", max: 65, description: "Version control, collaboration and open source." },
  { name: "Frontend Portfolio Project", max: 70, description: "Build and deploy real-world projects." },
];
const ICONS = [BookOpen, Code2, Sparkles, Wrench, LayoutDashboard, Github, FolderKanban];

function scoreForStage(stage, skills) {
  const names = new Set((skills || []).map((skill) => String(skill).toLowerCase()));
  const aliases = { "web foundations": ["html & css", "javascript"], "html & css": ["html & css"], javascript: ["javascript"], react: ["react"], "responsive design": ["html & css", "react"], "git & github": ["git & github"], "frontend portfolio project": ["react", "javascript"] };
  const matched = (aliases[stage.name.toLowerCase()] || []).filter((name) => names.has(name)).length;
  return matched ? Math.min(stage.max, Math.round(stage.max * (stage.name === "Frontend Portfolio Project" ? 0.2 : 0.5))) : 0;
}

export default function StudentDashboardRedesign({ student = {}, setActivePage }) {
  const careers = useMemo(() => { const selected = Array.isArray(student.careers) && student.careers.length ? student.careers : DEFAULT_CAREERS; return selected.slice(0, 3); }, [student.careers]);
  const [selectedCareer, setSelectedCareer] = useState(careers[0] || "Frontend Developer");
  const stageScores = useMemo(() => STAGES.map((stage) => ({ ...stage, score: scoreForStage(stage, student.skills) })), [student.skills]);
  const completed = stageScores.filter((stage) => stage.score >= stage.max).length;
  const totalPossible = stageScores.reduce((sum, stage) => sum + stage.max, 0);
  const totalScore = stageScores.reduce((sum, stage) => sum + stage.score, 0);
  const learningProgress = totalPossible ? Math.round((totalScore / totalPossible) * 100) : 0;
  const verified = Array.isArray(student.skills) ? student.skills.length : 0;
  const go = (page) => setActivePage?.(page);

  return <div className="min-h-full bg-slate-50 text-slate-900 -m-6">
    <header className="sticky top-0 z-20 h-[74px] bg-white/95 backdrop-blur border-b border-slate-200 flex items-center justify-between px-6 lg:px-8">
      <div><p className="text-[13px] font-medium text-slate-400">SkillProof workspace</p><h1 className="text-[18px] font-bold leading-5">Student Dashboard</h1><p className="hidden md:block text-xs text-slate-400 mt-0.5">Build skills. Get verified. Land opportunities.</p></div>
      <div className="flex items-center gap-3"><div className="hidden lg:flex items-center gap-2 w-[310px] h-10 px-3 rounded-xl border border-slate-200 bg-white text-slate-400"><Search size={17}/><span className="text-xs">Search skills, jobs, or opportunities...</span></div><button type="button" className="relative w-10 h-10 rounded-xl flex items-center justify-center" aria-label="Notifications"><Bell size={19}/><span className="absolute top-2 right-2 w-2 h-2 rounded-full bg-red-500"/></button><div className="hidden sm:flex items-center gap-2 pl-2"><div className="w-10 h-10 rounded-full bg-teal-50 border border-teal-100 text-teal-700 flex items-center justify-center font-bold text-sm">{(student.name || "OM").slice(0,2).toUpperCase()}</div><div className="leading-tight"><p className="text-sm font-bold">{student.name || "Student"}</p><p className="text-xs text-slate-400">Student</p></div></div></div>
    </header>
    <div className="grid lg:grid-cols-[254px_minmax(0,1fr)] min-h-[calc(100vh-74px)]">
      <aside className="hidden lg:flex bg-white border-r border-slate-200 flex-col"><nav className="p-4 space-y-6">
        <NavSection title="OVERVIEW"><NavItem active icon={LayoutDashboard} label="Dashboard" onClick={() => go("dashboard")}/><NavItem icon={BookOpen} label="My Learning" onClick={() => go("roadmap")}/><NavItem icon={Award} label="Skill Gap" onClick={() => go("gaps")}/><NavItem icon={Target} label="Roadmap" onClick={() => go("roadmap")}/></NavSection>
        <NavSection title="SKILLS"><NavItem icon={BookOpen} label="My Skills" onClick={() => go("skills")}/><NavItem icon={ShieldCheck} label="Verify Skills" onClick={() => go("verify")}/><NavItem icon={Award} label="Certificates" onClick={() => go("verify")}/><NavItem icon={FolderKanban} label="Projects" onClick={() => go("opportunities")}/></NavSection>
        <NavSection title="OPPORTUNITIES"><NavItem icon={BriefcaseBusiness} label="Internships & Jobs" onClick={() => go("opportunities")}/><NavItem icon={Users} label="Hackathons" onClick={() => go("opportunities")}/><NavItem icon={Sparkles} label="Recommendations" onClick={() => go("opportunities")}/></NavSection>
        <NavSection title="ACCOUNT"><NavItem icon={User} label="My Profile" onClick={() => go("profile")}/><NavItem icon={Settings} label="Settings" onClick={() => go("settings")}/></NavSection>
      </nav><div className="mt-auto p-4 border-t border-slate-100"><div className="rounded-2xl bg-amber-50/70 border border-amber-100 p-4"><div className="flex items-center gap-2 text-amber-700"><Sparkles size={17}/><span className="font-bold text-sm">Keep Learning!</span></div><p className="text-xs text-slate-500 mt-1">Consistency today builds your dream tomorrow.</p></div></div></aside>
      <main className="min-w-0 p-5 lg:p-8 overflow-hidden"><div className="max-w-[1280px] mx-auto">
        <section className="rounded-2xl border border-teal-100 bg-gradient-to-r from-teal-50/80 to-white px-5 lg:px-7 py-5 mb-5 flex items-center justify-between gap-6"><div><p className="text-xs font-bold tracking-[0.16em] text-teal-700">WELCOME BACK</p><h2 className="text-2xl lg:text-[29px] font-bold mt-1">Hi, {student.name || "Student"}! 👋</h2><p className="text-sm text-slate-500 mt-1">Here is your SkillProof progress for today.</p></div><div className="hidden md:block text-right"><p className="text-sm text-slate-500 max-w-[300px]">“Consistent learning today builds your dream tomorrow.”</p><p className="text-sm font-bold text-teal-700 mt-2">Keep going!</p></div></section>
        <section className="mb-5"><div className="flex items-end justify-between gap-4 mb-3"><div><p className="text-xs font-bold tracking-[0.16em] text-teal-700">CAREER FOCUS</p><h2 className="text-[29px] font-bold tracking-tight mt-1">Career readiness</h2><p className="text-sm text-slate-500 mt-1">Explore the complete skill path for your target career. Learn step by step and become job ready.</p></div><button type="button" onClick={() => go("careers")} className="hidden sm:flex items-center gap-2 px-4 py-2.5 rounded-xl border border-teal-200 text-teal-700 bg-white text-sm font-semibold hover:bg-teal-50"><Target size={16}/> Change Career Focus</button></div><div className="flex gap-2 overflow-x-auto pb-1">{careers.map((career,index)=><button key={career} type="button" onClick={() => setSelectedCareer(career)} className={`shrink-0 px-4 py-2.5 rounded-xl border text-sm font-medium transition ${selectedCareer===career ? "border-teal-400 bg-teal-50 text-teal-800" : "border-slate-200 bg-white text-slate-600 hover:border-slate-300"}`}>{career}<span className="ml-2 text-[10px] uppercase tracking-wide text-slate-400">{index===0?"Primary":"Target"}</span></button>)}</div></section>
        <div className="grid xl:grid-cols-[minmax(0,1fr)_360px] gap-5"><div className="min-w-0">
          <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3 mb-5"><Metric icon={BookOpen} label="Learning Progress" value={`${learningProgress}%`} note={`${completed} of ${STAGES.length} stages completed`} progress={learningProgress}/><Metric icon={ShieldCheck} label="Skills Verified" value={verified} note="Skills in your profile" progress={Math.min(100,verified*7)}/><Metric icon={FolderKanban} label="Projects Completed" value="0" note="Build your portfolio" progress={0}/><Metric icon={BriefcaseBusiness} label="Opportunities" value="0" note="Relevant matches" progress={0}/></section>
          <section className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="px-5 py-4 flex items-center justify-between border-b border-slate-100"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-600 flex items-center justify-center"><Target size={19}/></div><div><h3 className="font-bold text-lg">Complete skill path for {selectedCareer}</h3><p className="text-xs text-slate-400">Follow these 7 stages to master the required skills.</p></div></div><button type="button" onClick={() => go("roadmap")} className="hidden sm:flex items-center gap-2 px-3 py-2 rounded-xl border border-slate-200 text-xs font-semibold">View Full Path <ArrowRight size={14}/></button></div><div className="p-3 space-y-2">{stageScores.map((stage,index)=>{const Icon=ICONS[index];const locked=index>completed&&stage.score===0;return <div key={stage.name} className={`rounded-xl border p-3 flex items-center gap-3 ${index===completed?"border-teal-200 bg-teal-50/30":"border-slate-200 bg-white"}`}><div className="w-9 h-9 rounded-full bg-slate-50 border border-slate-200 flex items-center justify-center shrink-0"><span className="text-sm font-bold">{index+1}</span></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><div><p className="font-bold text-sm">{stage.name}</p><p className="text-[11px] text-slate-400 truncate">{stage.description}</p></div><div className="hidden sm:flex items-center gap-3"><span className="text-xs font-bold text-teal-600">{stage.score}/{stage.max}</span><span className="px-3 py-1 rounded-full bg-slate-100 text-[11px] text-slate-500">{stage.score>=stage.max?"Completed":locked?"Locked":"Not started"}</span></div></div><div className="h-1.5 bg-slate-100 rounded-full mt-2 overflow-hidden"><div className="h-full bg-teal-400 rounded-full" style={{width:`${Math.min(100,(stage.score/stage.max)*100)}%`}}/></div></div><Icon size={15} className="text-slate-300 hidden md:block"/></div>})}</div></section>
        </div><aside className="space-y-5">
          <section className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><div className="flex items-start justify-between"><div className="flex gap-3"><div className="w-11 h-11 rounded-xl bg-teal-50 text-teal-600 flex items-center justify-center"><Target size={20}/></div><div><p className="text-xs font-semibold text-slate-400">Target Career</p><h3 className="font-bold text-lg mt-1">{selectedCareer}</h3></div></div><button type="button" onClick={() => go("careers")} className="text-blue-600 text-xs font-semibold flex items-center gap-1"><Pencil size={12}/> Edit</button></div><p className="text-xs text-slate-400 mt-3">Build practical skills and evidence for your target role.</p></section>
          <section className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><div className="flex items-center justify-between mb-3"><h3 className="font-bold">Skill Summary</h3><span className="text-xs text-slate-400">{STAGES.length} stages</span></div><div className="space-y-3">{stageScores.map(stage=><div key={stage.name}><div className="flex justify-between text-xs"><span className="text-slate-600">{stage.name}</span><span className="text-slate-400">{stage.score}/{stage.max}</span></div><div className="h-1.5 bg-slate-100 rounded-full mt-1.5"><div className="h-full bg-teal-300 rounded-full" style={{width:`${(stage.score/stage.max)*100}%`}}/></div></div>)}</div><button type="button" onClick={() => go("roadmap")} className="mt-4 text-sm font-semibold text-teal-700 flex items-center gap-1">Open full skill tree <ArrowRight size={14}/></button></section>
          <section className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><div className="flex items-center gap-3 mb-3"><div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center"><Lightbulb size={19}/></div><div><h3 className="font-bold">Recommended for you</h3><p className="text-xs text-slate-400">Based on your career focus</p></div></div><Recommendation icon={FolderKanban} title="Build Your First Portfolio" text="A step-by-step guide to creating a standout portfolio." onClick={() => go("opportunities")}/><Recommendation icon={Sparkles} title="Top Frontend Projects" text="Hands-on projects to boost your skills." onClick={() => go("opportunities")}/><Recommendation icon={BriefcaseBusiness} title="Internships for Developers" text="Find opportunities that match your skills." onClick={() => go("opportunities")}/></section>
          <section className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><CheckCircle2 size={19} className="text-teal-600"/><h3 className="font-bold">Recent Activity</h3></div><button type="button" className="text-xs text-blue-600 font-semibold">View all</button></div><div className="py-7 text-center"><div className="mx-auto w-10 h-10 rounded-xl bg-slate-50 flex items-center justify-center text-slate-300"><BookOpen size={19}/></div><p className="text-sm text-slate-500 mt-2">No recent activity</p><p className="text-xs text-slate-400 mt-1">Start learning to see your activity here.</p></div></section>
        </aside></div>
      </div></main>
    </div>
  </div>;
}

function NavSection({ title, children }) { return <div><p className="px-3 mb-2 text-[11px] font-bold tracking-[0.16em] text-slate-400">{title}</p><div className="space-y-1">{children}</div></div>; }
function NavItem({ icon: Icon, label, active, onClick }) { return <button type="button" onClick={onClick} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-left text-sm ${active?"bg-teal-50 text-teal-700 font-semibold":"text-slate-500 hover:bg-slate-50 hover:text-slate-800"}`}><Icon size={17}/>{label}</button>; }
function Metric({ icon: Icon, label, value, note, progress }) { return <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-600 flex items-center justify-center"><Icon size={19}/></div><div><p className="text-xs text-slate-400">{label}</p><p className="text-xl font-bold mt-0.5">{value}</p></div></div><p className="text-[11px] text-slate-400 mt-2">{note}</p><div className="h-1.5 bg-slate-100 rounded-full mt-2 overflow-hidden"><div className="h-full bg-teal-300 rounded-full" style={{width:`${progress}%`}}/></div></div>; }
function Recommendation({ icon: Icon, title, text, onClick }) { return <button type="button" onClick={onClick} className="w-full flex items-center gap-3 text-left border border-slate-200 rounded-xl p-3 mb-2 hover:border-teal-200 hover:bg-teal-50/30"><div className="w-9 h-9 rounded-xl bg-slate-50 text-teal-600 flex items-center justify-center shrink-0"><Icon size={16}/></div><div className="min-w-0 flex-1"><p className="text-xs font-bold">{title}</p><p className="text-[10px] text-slate-400 mt-0.5 truncate">{text}</p></div><ChevronRight size={15} className="text-slate-300"/></button>; }
